[package]
name = "ceres"
version = "0.1.0"
license = "MIT"
edition = "2021"
description = "A Gameboy/Color emulator"

[dependencies]
ceres-core = { path = "../ceres-core" }
glutin = { version = "*", default-features = false, features = ["x11"] }
simplelog = "*"
colorful = "*"
clap = { version = "*", default-features = false, features = ["std"] }
log = "*"
cpal = "*"
dasp_ring_buffer = "*"
parking_lot = "*"
gl = "*"
rfd = "*"
