[package]
name = "ceres"
version = "0.1.0"
license = "MIT"
edition = "2021"
description = "A Gameboy/Color emulator"

[dependencies]
ceres-core = { path = "../ceres-core" }
clap = { version = "*", default-features = false, features = ["std"] }
log = "*"
sdl2 = { version = "*", features = ["unsafe_textures"] }
