[workspace]
members = ["ceres-core", "ceres"]
default-members = ["ceres"]

[profile.dev]
opt-level = 0
debug = 2
debug-assertions = true
overflow-checks = true
lto = "off"
panic = "unwind"
incremental = true
codegen-units = 2

[profile.test]
opt-level = 3
debug = 0
debug-assertions = true
overflow-checks = true
lto = "thin"
panic = "unwind"
incremental = true
codegen-units = 2

[profile.release]
opt-level = "s"
debug = 0
debug-assertions = false
overflow-checks = false
lto = "fat"
codegen-units = 1
panic = "abort"
incremental = true
strip = true
