[workspace]
members = ["ceres-core", "ceres"]
default-members = ["ceres"]

[profile.dev]
opt-level = 0
debug = 2

[profile.test]
opt-level = 3
debug = 0

[profile.release]
opt-level = "s"
debug = 0
lto = "fat"
codegen-units = 1
panic = "abort"
incremental = true
strip = true
