[workspace]
members = [
    "ceres-core",
    "ceres-glfw",
    "ceres-opengl",
    "ceres-cpal",
    "ceres-cli",
]
default-members = ["ceres-glfw"]

[profile.dev]
opt-level = 1
debug = 2
debug-assertions = true
overflow-checks = true
lto = "off"
panic = "unwind"
incremental = true
codegen-units = 16

[profile.test]
opt-level = 3
debug = 0
debug-assertions = true
overflow-checks = true
lto = "thin"
panic = "unwind"
incremental = true
codegen-units = 16

[profile.release]
opt-level = "s"
debug = 0
debug-assertions = false
overflow-checks = false
lto = "fat"
codegen-units = 1
panic = "abort"
incremental = true
strip = true
